config/routes.rb
Rails.application.routes.draw do
  post 'orders' => 'orders#create'
  get 'orders' => 'orders#index'
  get 'orders/:id' => 'orders#show'
  delete 'orders/:id/destroy' => 'orders#destroy'

  root 'products#root'
  resources :products do
    resources :reviews, only: [:index, :new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true

  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items


  def valid_order
    self.line_items.each do |line_item|
      begin
        product = Product.find(line_item.product_id)
      rescue ActiveRecord::RecordNotFound
        errors.add(:no_product, "The product does not exist")
        return false 
      end
      if line_item.quantity > product.stock
        errors.add(:no_stock, "There is not enough stock")
        return false 
      end
    end
    return true
  end

  def reduce_stock
    if self.line_items.empty?
      errors.add(:empty, "No products in order")
      return false
    end
    self.line_items.each do |line_item|
      product = Product.find(line_item.product_id)
      product.update({stock: product.stock - line_item.quantity})
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :line_items, dependent: :destroy
	has_many :orders, through: :line_items
	validates :name, presence: true

	def self.search(search, instock)
		if search
			if instock
				Product.where("name like ?", "%#{search}%").where("stock > ?", 0)
			else
				Product.where("name like ?", "%#{search}%")
			end
		else
			@products = Product.all
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[show destroy]
  
  def create
    @order = Order.new({name: order_params[:name]})
    respond_to do |format|
      unless @order.save
        format.html { redirect_to products_url, status: :conflict }
        format.json { render json: @order.errors, status: :conflict }
      else 
        params[:order][:products].each do |k,v|
          @line_item = LineItem.new({quantity: v, product_id: k, order_id: @order.id})
          @order.line_items << @line_item
        end
        if @order.valid_order
          @order.save
          @order.reduce_stock
          format.html { redirect_to products_url}
          format.json { render json: @order.errors, status: :created }
        else
          @order.destroy!
          format.html { render :new, status: :conflict }
          format.json { render json: @order.errors, status: :conflict }
        end
      end
    end
  end

  def index
    @orders = Order.all
  end

  def show
  end

  def destroy
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name, :products => {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def root
    redirect_to products_url
  end

  # GET /products or /products.json
  def index
    @products = Product.search(params[:search], params[:instock])
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :stock, :dimensions => [:x, :y, :z])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product, only: %i[ index ]
  def index
    @reviews = @product.reviews
    respond_to do |format|
      format.html { render :index, status: :ok }
      format.json { render json: @reviews, status: :ok }
    end
  end

  def create
    @product = Product.find(params[:product_id])
    @product.reviews_will_change!
    puts @product.name
    @product.reviews << params[:rating].to_i
    respond_to do |format|
      if @product.save!
        format.html { redirect_to product_reviews_url}
        format.json { render :index, status: :created, location: @reviews }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  def new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:product_id])
    end
    # Only allow a list of trusted parameters through.
    def reviews_params
      params.permit(:rating, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Orders</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name%></td>
        <% order.line_items.each do |line_item| %>
          <td>
            <%= link_to line_item.product_id, "/products/#{line_item.product_id}" %>
            :
            <%= line_item.quantity %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :dimensions %>
    <%= form.text_field :dimensions %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag products_path, :method => "get" do %>
  <%= label_tag(:search, "Search: ") %>
  <%= text_field_tag(:search, params[:search]) %>
  
  <%= label_tag(:instock, "In Stock: ") %>
  <%= check_box_tag(:instock, params[:instock]) %>
  </br>
  <%= submit_tag("Search", :name => nil) %>
<% end %>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Dimensions</th>
      <th>Stock</th>
      <th>Reviews</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.dimensions %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Reviews', product_reviews_path(product) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @product.dimensions %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/index.html.erb
<% @reviews.each do |review|%>
  <%= review %>
  </br>
<% end %>
<%= link_to 'New Review', new_product_review_path %>

app/views/reviews/new.html.erb
<%= form_with url: product_reviews_path, method: :post do |form| %>
  <%= form.label :rating, "Rating: " %>
  <%= form.text_field :rating %>
  <%= form.submit "Add" %>
<% end %>